Description: Creating a User with some basic permissions

Parameters:
  UserName:
    Description: Username
    Type: String
  UserPassword:
    Description: User password
    Type: String
  Department:
    Description: User belongs to...?
    Type: String

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
      Tags:
        - Key: Department
          Value: !Ref Department

  BasicCustomIAMPermissions:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: OwnAccessKeysAndMFA
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iam:CreateAccessKey
              - iam:DeleteAccessKey
              - iam:GetAccessKeyLastUsed
              - iam:GetUser
              - iam:ListAccessKeys
              - iam:UpdateAccessKey
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:DeactivateMFADevice
              - iam:DeleteVirtualMFADevice
              - iam:EnableMFADevice
              - iam:ResyncMFADevice
              - iam:CreateVirtualMFADevice
              - iam:ListMFADevices
            Resource: '*'
      Users:
        - !Ref User
